# Copyright (c) IBM Corporation.
# Copyright (c) Microsoft Corporation.
- name: CLIENT_ID
  value: ""
  description: Client ID for an Azure AD application registered in the **Partner Center**
- name: SECRET_VALUE
  value: ""
  description: Secret value of the Azure AD application registered in the **Partner Center**
- name: TENANT_ID
  value: ""
  description: Tenant ID of the Azure AD application registered in the **Partner Center**
- name: USER_NAME
  value: ""
  description: User name of GitHub account
# The base64 encoded pull secret text.
# See https://learn.microsoft.com/en-us/azure/openshift/tutorial-create-cluster?WT.mc_id=Portal-fx#get-a-red-hat-pull-secret-optional to obtain the pull secret from the Red Hat OpenShift Cluster Manager website.
# Run "echo '<pull-secret-text>' | base64 -w0" to encode the pull secret.
- name: PULL_SECRET_ENCODED
  value: ""
  description: The base64 encoded pull secret text.
## Optional parameters: if you want to use optional parameters, please uncomment the following lines
#- name: MSTEAMS_WEBHOOK
#  value: ""
#  description: [Optional] Web hook for Microsoft Teams channel
